
Options in effect for LPGParser.g:

    ACTION-BLOCK=("LPGParser.rs","/.","./")

    AST-DIRECTORY=""  AST-TYPE="Ast"  NOATTRIBUTES  NOAUTOMATIC-AST  NOBACKTRACK
    BYTE  CONFLICTS  DAT-DIRECTORY=""  DAT-FILE="LPGParserdcl.data"  
    DCL-FILE="LPGParserdcl.rs"  NODEBUG  DEF-FILE="LPGParserdef.rs"  
    DIRECTORY-PREFIX=""  NOEDIT  ERROR-MAPS  ESCAPE='$'  
    EXPORT-TERMINALS=("LPGParserexp.rs","","")  EXTENDS-PARSETABLE  FACTORY=""
    FILE-PREFIX="LPGParser"  NOFIRST  NOFOLLOW  NOGLR  NOGOTO-DEFAULT  
    GRM-FILE="LPGParser.g"  IMP-FILE="LPGParserimp.rs"  
    IMPORT-TERMINALS="LPGLexer.gi"  
    INCLUDE-DIRECTORY="/Users/kuafu/workspace/lpg-project/LPG2/lpg2/../lpg-generator-templates-2.1.00/include/rust"
    LALR=6  LEGACY  NOLIST  MARGIN=4  MAX-CASES=1024  NAMES=OPTIMIZED  
    NONT-CHECK  OR_MARKER='|'  OUT-DIRECTORY=""  PACKAGE="lpg"  NOPARENT-SAVE  
    PARSETABLE-INTERFACES="ParseTable"  PREFIX="TK_"  PRIORITY  
    PROGRAMMING_LANGUAGE=RUST  PRS-FILE="LPGParserprs.rs"  NOQUIET  READ-REDUCE
    REMAP-TERMINALS  RULE_CLASSNAMES=SEQUENTIAL  SCOPES  NOSERIALIZE  
    NOSHIFT-DEFAULT  NOSINGLE-PRODUCTIONS  NOSOFT-KEYWORDS  NOSTATES  SUFFIX=""
    SYM-FILE="LPGParsersym.rs"  TAB-FILE="LPGParser.t"  TABLE  
    TEMPLATE="/Users/kuafu/workspace/lpg-project/LPG2/lpg2/../lpg-generator-templates-2.1.00/templates/rust/dtParserTemplateF.gi"
    TRACE=CONFLICTS  NOVARIABLES  NOVERBOSE  NOVISITOR  VISITOR-TYPE="Visitor"
    WARNINGS  NOXREF  

LPGParser.g:28:5:28:16:474:485: Informative: The terminal LEFT_BRACKET is useless.
LPGParser.g:29:5:29:17:499:511: Informative: The terminal RIGHT_BRACKET is useless.
LPGParser.g:30:5:30:9:525:529: Informative: The terminal SHARP is useless.
LPGLexer.gi:27:5:27:23:330:348: Informative: The terminal SINGLE_LINE_COMMENT is useless.
LPGLexer.gi:44:5:44:8:575:578: Informative: The terminal VBAR is useless.


LPGParser.g:34:5:34:7:556:558: Informative: Grammar is  LALR(3).

Number of Terminals: 47
Number of Nonterminals: 67
Number of Productions: 148
Number of Items: 400
Number of Scopes: 0
Number of States: 105
Number of look-ahead states: 9
Number of Shift actions: 127
Number of Goto actions: 68
Number of Shift/Reduce actions: 212
Number of Goto/Reduce actions: 84
Number of Reduce actions: 1355
Number of Shift-Reduce conflicts: 0
Number of Reduce-Reduce conflicts: 0

Number of entries in base Action Table: 257
Additional space required for compaction of Action Table: 18.6%

Number of unique terminal states: 70
Number of Shift actions saved by merging: 125
Number of Conflict points saved by merging: 0
Number of Reduce actions saved by merging: 450
Number of Reduce saved by default: 904

Number of entries in Terminal Action Table: 294
Additional space required for compaction of Terminal Table: 1.0%

Actions in Compressed Tables:
     Number of Shifts: 126
     Number of Shift/Reduces: 88
     Number of Look-Ahead Shifts: 9
     Number of Gotos: 68
     Number of Goto/Reduces: 84
     Number of Reduces: 1
     Number of Defaults: 47

Parsing Tables storage:
    Storage required for BASE_CHECK: 453 Bytes
    Storage required for BASE_ACTION: 908 Bytes
    Storage required for TERM_CHECK: 342 Bytes
    Storage required for TERM_ACTION: 596 Bytes

Error maps storage:
    Storage required for ACTION_SYMBOLS_BASE map: 212 Bytes
    Storage required for ACTION_SYMBOLS_RANGE map: 200 Bytes
    Storage required for NACTION_SYMBOLS_BASE map: 106 Bytes
    Storage required for NACTION_SYMBOLS_RANGE map: 117 Bytes
    Storage required for TERMINAL_INDEX map: 48 Bytes
    Storage required for NON_TERMINAL_INDEX map: 69 Bytes

    Number of names: 96
    Number of characters in name: 967
